export const seedInterns = [
  {
    id: 'ID01',
    name: 'Anurag',
    role: 'Frontend Intern',
    email: 'alice.johnson@example.com',
    phone: '(555) 123-4567',
    imageUrl: '/interns/Anurag.webp',
    projects: ['Marketing site revamp', 'Design system'],
    manager: 'Priya Nair',
    startDate: '2026-01-06',
    performance: 'Great communication and consistent delivery.',
    skills: ['React', 'CSS', 'Figma'],
    department: 'Design',
  },
  {
    id: 'ID02',
    name: 'Ashish',
    role: 'Backend Intern',
    email: 'ben.carter@example.com',
    phone: '(555) 234-5678',
    imageUrl: '/interns/Ashish.webp',
    projects: ['Auth service', 'API optimization'],
    manager: 'Luis Ortega',
    startDate: '2026-01-13',
    performance: 'Strong debugging skills and rapid learning.',
    skills: ['Node.js', 'Postgres', 'Docker'],
    department: 'Engineering',
  },
  {
    id: 'ID03',
    name: 'Gabriel',
    role: 'Fullstack Intern',
    email: 'clara.lee@example.com',
    phone: '(555) 345-6789',
    imageUrl: '/interns/Gabriel.webp',
    projects: ['Internal tools'],
    manager: 'Mira Patel',
    startDate: '2026-01-20',
    performance: 'Owns tasks end-to-end and seeks feedback.',
    skills: ['React', 'TypeScript', 'Node.js'],
    department: 'Product',
  },
  {
    id: 'ID04',
    name: 'Karen',
    role: 'Data Intern',
    email: 'diego.alvarez@example.com',
    phone: '(555) 456-7890',
    imageUrl: '/interns/Karen.webp',
    projects: ['ETL cleanup', 'Dashboard metrics'],
    manager: 'Hannah Brooks',
    startDate: '2026-01-08',
    performance: 'Methodical and detail-oriented.',
    skills: ['Python', 'SQL', 'Tableau'],
    department: 'Data',
  },
  {
    id: 'ID05',
    name: 'Dickens',
    role: 'Design Intern',
    email: 'elena.park@example.com',
    phone: '(555) 567-8901',
    imageUrl: '/public/interns/Dickens.webp',
    projects: ['Onboarding flow', 'Illustrations'],
    manager: 'Priya Nair',
    startDate: '2026-01-09',
    performance: 'Strong visual storytelling.',
    skills: ['Figma', 'Illustrator', 'UX'],
    department: 'Design',
  },
  {
    id: 'ID06',
    name: 'Donald',
    role: 'Design Intern',
    email: 'donald.harris@example.com',
    phone: '(555) 678-9012',
    imageUrl: '/public/interns/Donald.webp',
    projects: ['Onboarding flow', 'Illustrations'],
    manager: 'Priya Nair',
    startDate: '2026-01-09',
    performance: 'Strong visual storytelling.',
    skills: ['Figma', 'Illustrator', 'UX'],
    department: 'Design',
  },
]
