export const seedInterns = [
  {
    id: 'INT-001',
    name: 'Alice Johnson',
    role: 'Frontend Intern',
    email: 'alice.johnson@example.com',
    phone: '(555) 123-4567',
    projects: ['Marketing site revamp', 'Design system'],
    manager: 'Priya Nair',
    startDate: '2026-01-06',
    performance: 'Great communication and consistent delivery.',
    skills: ['React', 'CSS', 'Figma'],
    department: 'Design',
  },
  {
    id: 'INT-002',
    name: 'Ben Carter',
    role: 'Backend Intern',
    email: 'ben.carter@example.com',
    phone: '(555) 234-5678',
    projects: ['Auth service', 'API optimization'],
    manager: 'Luis Ortega',
    startDate: '2026-01-13',
    performance: 'Strong debugging skills and rapid learning.',
    skills: ['Node.js', 'Postgres', 'Docker'],
    department: 'Engineering',
  },
  {
    id: 'INT-003',
    name: 'Clara Lee',
    role: 'Fullstack Intern',
    email: 'clara.lee@example.com',
    phone: '(555) 345-6789',
    projects: ['Internal tools'],
    manager: 'Mira Patel',
    startDate: '2026-01-20',
    performance: 'Owns tasks end-to-end and seeks feedback.',
    skills: ['React', 'TypeScript', 'Node.js'],
    department: 'Product',
  },
  {
    id: 'INT-004',
    name: 'Diego Alvarez',
    role: 'Data Intern',
    email: 'diego.alvarez@example.com',
    phone: '(555) 456-7890',
    projects: ['ETL cleanup', 'Dashboard metrics'],
    manager: 'Hannah Brooks',
    startDate: '2026-01-08',
    performance: 'Methodical and detail-oriented.',
    skills: ['Python', 'SQL', 'Tableau'],
    department: 'Data',
  },
  {
    id: 'INT-005',
    name: 'Elena Park',
    role: 'Design Intern',
    email: 'elena.park@example.com',
    phone: '(555) 567-8901',
    projects: ['Onboarding flow', 'Illustrations'],
    manager: 'Priya Nair',
    startDate: '2026-01-09',
    performance: 'Strong visual storytelling.',
    skills: ['Figma', 'Illustrator', 'UX'],
    department: 'Design',
  },
  {
    id: 'INT-006',
    name: 'Farah Ahmed',
    role: 'Frontend Intern',
    email: 'farah.ahmed@example.com',
    phone: '(555) 678-9012',
    projects: ['Component library', 'Landing page'],
    manager: 'Ethan Reed',
    startDate: '2026-01-10',
    performance: 'Great velocity with clean code.',
    skills: ['React', 'Tailwind', 'Storybook'],
    department: 'Engineering',
  },
  {
    id: 'INT-007',
    name: 'Gavin Brooks',
    role: 'Backend Intern',
    email: 'gavin.brooks@example.com',
    phone: '(555) 789-0123',
    projects: ['Billing service', 'Queue tuning'],
    manager: 'Luis Ortega',
    startDate: '2026-01-11',
    performance: 'Solid fundamentals and reliable.',
    skills: ['Node.js', 'Redis', 'Postgres'],
    department: 'Engineering',
  },
  {
    id: 'INT-008',
    name: 'Hana Kim',
    role: 'Product Intern',
    email: 'hana.kim@example.com',
    phone: '(555) 890-1234',
    projects: ['User interviews', 'Roadmap research'],
    manager: 'Mira Patel',
    startDate: '2026-01-12',
    performance: 'Insightful and organized.',
    skills: ['Research', 'Docs', 'Analytics'],
    department: 'Product',
  },
  {
    id: 'INT-009',
    name: 'Isaac Turner',
    role: 'QA Intern',
    email: 'isaac.turner@example.com',
    phone: '(555) 901-2345',
    projects: ['Regression suite', 'Bug triage'],
    manager: 'Nora Fields',
    startDate: '2026-01-14',
    performance: 'Thorough and proactive.',
    skills: ['Playwright', 'Jest', 'Reporting'],
    department: 'Engineering',
  },
  {
    id: 'INT-010',
    name: 'Jade Morgan',
    role: 'Marketing Intern',
    email: 'jade.morgan@example.com',
    phone: '(555) 012-3456',
    projects: ['Campaign assets', 'Email copy'],
    manager: 'Sophie Green',
    startDate: '2026-01-15',
    performance: 'Strong writing and cadence.',
    skills: ['Copywriting', 'Canva', 'SEO'],
    department: 'Marketing',
  },
  {
    id: 'INT-011',
    name: 'Kai Rivera',
    role: 'Fullstack Intern',
    email: 'kai.rivera@example.com',
    phone: '(555) 112-3456',
    projects: ['Admin portal', 'API docs'],
    manager: 'Ethan Reed',
    startDate: '2026-01-16',
    performance: 'Balances frontend and backend well.',
    skills: ['TypeScript', 'React', 'Node.js'],
    department: 'Engineering',
  },
  {
    id: 'INT-012',
    name: 'Lena Roberts',
    role: 'Data Intern',
    email: 'lena.roberts@example.com',
    phone: '(555) 123-9876',
    projects: ['Churn analysis', 'KPI definitions'],
    manager: 'Hannah Brooks',
    startDate: '2026-01-17',
    performance: 'Great analytical instincts.',
    skills: ['Python', 'SQL', 'Looker'],
    department: 'Data',
  },
  {
    id: 'INT-013',
    name: 'Marco Silva',
    role: 'Backend Intern',
    email: 'marco.silva@example.com',
    phone: '(555) 234-9876',
    projects: ['Webhook service', 'Rate limits'],
    manager: 'Luis Ortega',
    startDate: '2026-01-18',
    performance: 'Dependable and collaborative.',
    skills: ['Go', 'Postgres', 'Docker'],
    department: 'Engineering',
  },
  {
    id: 'INT-014',
    name: 'Nina Patel',
    role: 'Design Intern',
    email: 'nina.patel@example.com',
    phone: '(555) 345-9876',
    projects: ['Icon set', 'UI polish'],
    manager: 'Priya Nair',
    startDate: '2026-01-19',
    performance: 'Crisp execution and fast iterations.',
    skills: ['Figma', 'UI', 'Prototyping'],
    department: 'Design',
  },
  {
    id: 'INT-015',
    name: 'Omar Hassan',
    role: 'Security Intern',
    email: 'omar.hassan@example.com',
    phone: '(555) 456-9876',
    projects: ['Vuln scan', 'Auth review'],
    manager: 'Nora Fields',
    startDate: '2026-01-21',
    performance: 'Strong risk awareness.',
    skills: ['OWASP', 'Burp', 'Threat modeling'],
    department: 'Engineering',
  },
  {
    id: 'INT-016',
    name: 'Priya Shah',
    role: 'Product Intern',
    email: 'priya.shah@example.com',
    phone: '(555) 567-9876',
    projects: ['Competitor research', 'Feature specs'],
    manager: 'Mira Patel',
    startDate: '2026-01-22',
    performance: 'Clear and concise documentation.',
    skills: ['PRDs', 'Research', 'Roadmaps'],
    department: 'Product',
  },
  {
    id: 'INT-017',
    name: 'Quinn Parker',
    role: 'Frontend Intern',
    email: 'quinn.parker@example.com',
    phone: '(555) 678-9876',
    projects: ['Accessibility fixes', 'UI refactor'],
    manager: 'Ethan Reed',
    startDate: '2026-01-23',
    performance: 'Great focus on polish.',
    skills: ['React', 'A11y', 'CSS'],
    department: 'Engineering',
  },
  {
    id: 'INT-018',
    name: 'Riya Desai',
    role: 'Data Intern',
    email: 'riya.desai@example.com',
    phone: '(555) 789-9876',
    projects: ['Pipeline monitoring', 'Data QA'],
    manager: 'Hannah Brooks',
    startDate: '2026-01-24',
    performance: 'Consistent and careful.',
    skills: ['Python', 'Airflow', 'SQL'],
    department: 'Data',
  },
  {
    id: 'INT-019',
    name: 'Samir Khan',
    role: 'Backend Intern',
    email: 'samir.khan@example.com',
    phone: '(555) 890-9876',
    projects: ['Cache layer', 'Latency fixes'],
    manager: 'Luis Ortega',
    startDate: '2026-01-25',
    performance: 'Great debugging in production.',
    skills: ['Node.js', 'Redis', 'APIs'],
    department: 'Engineering',
  },
  {
    id: 'INT-020',
    name: 'Talia Woods',
    role: 'Marketing Intern',
    email: 'talia.woods@example.com',
    phone: '(555) 901-9876',
    projects: ['Social calendar', 'Brand voice'],
    manager: 'Sophie Green',
    startDate: '2026-01-26',
    performance: 'Creative and on-brand.',
    skills: ['Social', 'Copywriting', 'Branding'],
    department: 'Marketing',
  },
  {
    id: 'INT-021',
    name: 'Uma Rao',
    role: 'Fullstack Intern',
    email: 'uma.rao@example.com',
    phone: '(555) 112-9876',
    projects: ['Analytics UI', 'API gateway'],
    manager: 'Ethan Reed',
    startDate: '2026-01-27',
    performance: 'Balances priorities well.',
    skills: ['React', 'TypeScript', 'GraphQL'],
    department: 'Engineering',
  },
  {
    id: 'INT-022',
    name: 'Victor Chen',
    role: 'QA Intern',
    email: 'victor.chen@example.com',
    phone: '(555) 123-6789',
    projects: ['Test automation', 'Bug repros'],
    manager: 'Nora Fields',
    startDate: '2026-01-28',
    performance: 'Clear communication on issues.',
    skills: ['Cypress', 'Jest', 'Docs'],
    department: 'Engineering',
  },
  {
    id: 'INT-023',
    name: 'Willow Hart',
    role: 'Design Intern',
    email: 'willow.hart@example.com',
    phone: '(555) 234-6789',
    projects: ['Illustrations', 'Brand refresh'],
    manager: 'Priya Nair',
    startDate: '2026-01-29',
    performance: 'Consistent visual quality.',
    skills: ['Illustrator', 'Brand', 'Figma'],
    department: 'Design',
  },
  {
    id: 'INT-024',
    name: 'Xavier Brooks',
    role: 'Backend Intern',
    email: 'xavier.brooks@example.com',
    phone: '(555) 345-6781',
    projects: ['Log pipeline', 'Observability'],
    manager: 'Luis Ortega',
    startDate: '2026-01-30',
    performance: 'Reliable and thoughtful.',
    skills: ['Go', 'Kafka', 'Metrics'],
    department: 'Engineering',
  },
  {
    id: 'INT-025',
    name: 'Yara Malik',
    role: 'Product Intern',
    email: 'yara.malik@example.com',
    phone: '(555) 456-6781',
    projects: ['Customer feedback', 'Journey maps'],
    manager: 'Mira Patel',
    startDate: '2026-01-31',
    performance: 'Empathetic and organized.',
    skills: ['Research', 'Workshops', 'Docs'],
    department: 'Product',
  },
  {
    id: 'INT-026',
    name: 'Zane Powell',
    role: 'Frontend Intern',
    email: 'zane.powell@example.com',
    phone: '(555) 567-6781',
    projects: ['Responsive fixes', 'Animation polish'],
    manager: 'Ethan Reed',
    startDate: '2026-02-01',
    performance: 'Good eye for motion.',
    skills: ['React', 'CSS', 'Framer'],
    department: 'Engineering',
  },
  {
    id: 'INT-027',
    name: 'Aria Bennett',
    role: 'Data Intern',
    email: 'aria.bennett@example.com',
    phone: '(555) 678-6781',
    projects: ['Forecast model', 'Data cleanup'],
    manager: 'Hannah Brooks',
    startDate: '2026-02-02',
    performance: 'Strong modeling instincts.',
    skills: ['Python', 'Pandas', 'SQL'],
    department: 'Data',
  },
  {
    id: 'INT-028',
    name: 'Brent Lawson',
    role: 'Security Intern',
    email: 'brent.lawson@example.com',
    phone: '(555) 789-6781',
    projects: ['Access review', 'Policy updates'],
    manager: 'Nora Fields',
    startDate: '2026-02-03',
    performance: 'Thorough and calm under pressure.',
    skills: ['IAM', 'Audit', 'Compliance'],
    department: 'Engineering',
  },
  {
    id: 'INT-029',
    name: 'Chloe Nguyen',
    role: 'Marketing Intern',
    email: 'chloe.nguyen@example.com',
    phone: '(555) 890-6781',
    projects: ['Blog calendar', 'SEO refresh'],
    manager: 'Sophie Green',
    startDate: '2026-02-04',
    performance: 'Clear and consistent execution.',
    skills: ['SEO', 'Content', 'Analytics'],
    department: 'Marketing',
  },
  {
    id: 'INT-030',
    name: 'Dylan Ward',
    role: 'Fullstack Intern',
    email: 'dylan.ward@example.com',
    phone: '(555) 901-6781',
    projects: ['Partner portal', 'Data sync'],
    manager: 'Ethan Reed',
    startDate: '2026-02-05',
    performance: 'Good ownership and follow-through.',
    skills: ['React', 'Node.js', 'SQL'],
    department: 'Engineering',
  },
  {
    id: 'INT-031',
    name: 'Emily White',
    role: 'Frontend Intern',
    email: 'emily.white@example.com',
    phone: '(555) 102-3456',
    projects: ['User Dashboard', 'Component Library'],
    manager: 'Ethan Reed',
    startDate: '2026-02-06',
    performance: 'Quick learner with attention to detail.',
    skills: ['React', 'TypeScript', 'CSS'],
    department: 'Engineering',
  },
  {
    id: 'INT-032',
    name: 'Frank Green',
    role: 'Backend Intern',
    email: 'frank.green@example.com',
    phone: '(555) 203-4567',
    projects: ['Database Optimization', 'API Security'],
    manager: 'Luis Ortega',
    startDate: '2026-02-07',
    performance: 'Proactive in identifying and resolving issues.',
    skills: ['Node.js', 'PostgreSQL', 'Docker'],
    department: 'Engineering',
  },
  {
    id: 'INT-033',
    name: 'Grace Hall',
    role: 'UX/UI Intern',
    email: 'grace.hall@example.com',
    phone: '(555) 304-5678',
    projects: ['Mobile App Design', 'User Research'],
    manager: 'Priya Nair',
    startDate: '2026-02-08',
    performance: 'Excellent design sensibility and user empathy.',
    skills: ['Figma', 'Sketch', 'User Interviews'],
    department: 'Design',
  },
  {
    id: 'INT-034',
    name: 'Henry King',
    role: 'Data Science Intern',
    email: 'henry.king@example.com',
    phone: '(555) 405-6789',
    projects: ['Predictive Analytics', 'A/B Testing'],
    manager: 'Hannah Brooks',
    startDate: '2026-02-09',
    performance: 'Strong analytical skills and problem-solving.',
    skills: ['Python', 'R', 'Machine Learning'],
    department: 'Data',
  },
  {
    id: 'INT-035',
    name: 'Ivy Lee',
    role: 'DevOps Intern',
    email: 'ivy.lee@example.com',
    phone: '(555) 506-7890',
    projects: ['CI/CD Pipeline', 'Cloud Infrastructure'],
    manager: 'Nora Fields',
    startDate: '2026-02-10',
    performance: 'Detail-oriented and efficient in automation.',
    skills: ['AWS', 'Kubernetes', 'Jenkins'],
    department: 'Engineering',
  },
  {
    id: 'INT-036',
    name: 'Jack Miller',
    role: 'Product Management Intern',
    email: 'jack.miller@example.com',
    phone: '(555) 607-8901',
    projects: ['Market Research', 'Feature Definition'],
    manager: 'Mira Patel',
    startDate: '2026-02-11',
    performance: 'Strategic thinker with great communication.',
    skills: ['Jira', 'Agile', 'Roadmapping'],
    department: 'Product',
  },
  {
    id: 'INT-037',
    name: 'Karen Nash',
    role: 'Content Marketing Intern',
    email: 'karen.nash@example.com',
    phone: '(555) 708-9012',
    projects: ['Blog Posts', 'Social Media Campaigns'],
    manager: 'Sophie Green',
    startDate: '2026-02-12',
    performance: 'Creative writer with strong engagement skills.',
    skills: ['SEO', 'Copywriting', 'Social Media'],
    department: 'Marketing',
  },
  {
    id: 'INT-038',
    name: 'Leo Perez',
    role: 'Cybersecurity Intern',
    email: 'leo.perez@example.com',
    phone: '(555) 809-0123',
    projects: ['Vulnerability Testing', 'Security Audits'],
    manager: 'Nora Fields',
    startDate: '2026-02-13',
    performance: 'Thorough and meticulous in security analysis.',
    skills: ['Penetration Testing', 'Network Security', 'Compliance'],
    department: 'Engineering',
  },
  {
    id: 'INT-039',
    name: 'Mia Quinn',
    role: 'Mobile Development Intern',
    email: 'mia.quinn@example.com',
    phone: '(555) 910-1234',
    projects: ['iOS App Feature', 'Bug Fixing'],
    manager: 'Ethan Reed',
    startDate: '2026-02-14',
    performance: 'Strong coding skills and attention to UI.',
    skills: ['Swift', 'Kotlin', 'React Native'],
    department: 'Engineering',
  },
  {
    id: 'INT-040',
    name: 'Noah Ross',
    role: 'Cloud Engineering Intern',
    email: 'noah.ross@example.com',
    phone: '(555) 011-2345',
    projects: ['Serverless Functions', 'Infrastructure Automation'],
    manager: 'Luis Ortega',
    startDate: '2026-02-15',
    performance: 'Efficient and knowledgeable in cloud technologies.',
    skills: ['AWS Lambda', 'Azure Functions', 'GCP'],
    department: 'Engineering',
  },
]
